#!/usr/bin/env python
import sys
from cookie_function import find_most_active_cookies

file_name = sys.argv[1]
# utc not used
# utc = sys.argv[2]
date_string = sys.argv[3]

cookies = find_most_active_cookies(file_name, date_string)
for cookie in cookies:
  print(cookie)